create table Reviews(
Id int identity(1,1) Primary key,
ProductId int FOREIGN KEY REFERENCES Product(ProductId),
UserName nvarchar(25),
Review nvarchar(max)  
)
insert into Reviews (ProductId,UserName,Review) values 
('1','roba','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt. Qui velit senserit constituam at, ad nihil melius numquam qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('2','lina','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('2','lina','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos ei. Vis consul epicuri consectetuer ne, quo volumus nominavi et. Errem impedit tibique pri ei, dicat aliquam ad usu. Vim eu aperiam omittam qualisque, sea laoreet electram in. Delectus verterem disputationi ad vim, eos ne inermis molestie consetetur, populo mnesarchum quo te.
Vel te mazim error diceret, per posidonium concludaturque ad. Qui te semper integre, an sed primis reprimique. Qui exerci verterem sententiae cu, probo dignissim expetendis mea no. Ad alienum repudiare mei. Sumo tacimates duo in, mei no doctus vocibus patrioque. Omnis paulo affert ad quo, dolore omittantur delicatissimi ne eam, quas deserunt at has.
Has id tation utinam. Alienum copiosae adolescens cum id. His et omnesque accusamus, tantas dolore te sed. Ea detracto epicurei inciderint mel, at utroque inimicus torquatos nam, sea no constituam scribentur reprehendunt.
Te epicuri iudicabit his. Qui velit senserit constituam at, ad nihil melius numquam qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('11','roba','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos ei. Vis consul epicuri consectetuer ne, quo volumus nominavi et. Errem impedit tibique pri ei, dicat aliquam ad usu. Vim eu aperiam omittam qualisque, sea laoreet electram in. Delectus verterem disputationi ad vim, eos ne inermis molestie consetetur, populo mnesarchum quo te.
Vel te mazim error diceret, per posidonium concludaturque ad. Qui te semper integre, an sed primis reprimique. Qui exerci verterem sententiae cu, probo dignissim expetendis mea no. Ad alienum repudiare mei. Sumo tacimates duo in, mei no doctus vocibus patrioque. Omnis paulo affert ad quo, dolore omittantur delicatissimi ne eam, quas deserunt at has.
Has id tation utinam. Alienum copiosae adolescens cum id. His et omnesque accusamus, tantas dolore te sed. Ea detracto epicurei inciderint mel, at utroque inimicus torquatos nam, sea no constituam scribentur reprehendunt.
Te epicuri iudicabit his. Qui velit senserit constituam at, ad nihil melius numquam qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('3','Ammar','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos ei. Vis consul epicuri consectetuer ne, quo volumus nominavi et. Errem impedit tibique pri ei, dicat aliquam ad usu. Vim eu aperiam omittam qualisque, sea laoreet electram in. Delectus verterem disputationi ad vim, eos ne inermis molestie consetetur, populo mnesarchum quo te.
Vel te mazim error diceret, per posidonium concludaturque ad. Qui te semper integre, an sed primis reprimique. Qui exerci verterem sententiae cu, probo dignissim expetendis mea no. Ad alienum repudiare mei. Sumo tacimates duo in, mei no doctus vocibus patrioque. Omnis paulo affert ad quo, dolore omittantur delicatissimi ne eam, quas deserunt at has.
Has id tation utinam. Alienum copiosae adolescens cum id. His et omnesque accusamus, tantas dolore te sed. Ea detracto epicurei inciderint mel, at utroque inimicus torquatos nam, sea no constituam scribentur reprehendunt.
Te epicuri iudicabit his. Qui velit senserit constituam at, ad nihil melius numquam qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('4','lina','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos ei. Vis consul epicuri consectetuer ne, quo volumus nominavi et. Errem impedit tibique pri ei, dicat aliquam ad usu. Vim eu aperiam omittam qualisque, sea laoreet electram in. Delectus verterem disputationi ad vim, eos ne inermis molestie consetetur, populo mnesarchum quo te.
Vel te mazim error diceret, per posidonium concludaturque ad. Qui te semper integre, an sed primis reprimique. Qui exerci verterem sententiae cu, probo dignissim expetendis mea no. Ad alienum repudiare mei. Sumo tacimates duo in, mei no doctus vocibus patrioque. Omnis paulo affert ad quo, dolore omittantur delicatissimi ne eam, quas deserunt at has.
Has id tation utinam. Alienum copiosae adolescens cum id. His et omnesque accusamus, tantas dolore te sed. Ea detracto epicurei inciderint mel, at utroque inimicus torquatos nam, sea no constituam scribentur reprehendunt.
Te epicuri iudicabit his. Qui velit senserit constituam at, ad nihil melius numquam qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('5','roba','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos ei. Vis consul epicuri consectetuer ne, quo volumus nominavi et. Errem impedit tibique pri ei, dicat aliquam ad usu. Vim eu aperiam omittam qualisque, sea laoreet electram in. Delectus verterem disputationi ad vim, eos ne inermis molestie consetetur, populo mnesarchum quo te.
Vel te mazim error diceret, per posidonium concludaturque ad. Qui te semper integre, an sed primis reprimique. Qui exerci verterem sententiae cu, probo dignissim expetendis mea no. Ad alienum repudiare mei. Sumo tacimates duo in, mei no doctus vocibus patrioque. Omnis paulo affert ad quo, dolore omittantur delicatissimi ne eam, quas deserunt at has.
Has id tation utinam. Alienum copiosae adolescens cum id. His et omnesque accusamus, tantas dolore te sed. Ea detracto epicurei inciderint mel, at utroque inimicus torquatos nam, sea no constituam scribentur reprehendunt.
Te epicuri iudicabit his. Qui velit senserit constituam at, ad nihil melius numquam qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('6','Ammar','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit,Ea detracto epicurei inciderint mel, at utroque inimicus torquatos nam, sea no constituam scribentur reprehendunt.
Te epicuri iudicabit his. Qui velit senserit constituam at, ad nihil melius numquam qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('7','lina','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos ei. Vis consul epicuri consectetuer ne, quo volumus nominavi et. Errem impedit tibique pri ei, dicat aliquam ad usu. Vim eu aperiam omittam qualisque, sea laoreet electram in. Delectus verterem disputationi ad vim, eos ne inermis molestie consetetur, populo mnesarchum quo te.
Vel te mazim error diceret, per posidonium concludaturque ad. Qui te semper integre, an sed primis reprimique. Qui exerci verterem sententiae cu, probo dignissim expetendis mea no. Ad alienum repudiare mei. Sumo tacimates duo in, mei no doctus vocibus patrioque. Omnis paulo affert ad quo, dolore omittantur delicatissimi ne eam, quas deserunt at has.
Has id tation utinam. Alienum copiosae adolescens cum id. His et omnesque accusamus, tantas dolore te sed. Ea detracto epicurei inciderint mel, at utroque inimicus torquatos nam, sea no constituam scribentur reprehendunt.
Te epicuri iudicabit his. Qui velit senserit constituam at, ad nihil melius numquam qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('8','roba','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('9','lina','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos ei. Vis consul epicuri consectetuer ne, quo volumus nominavi et. Errem impedit tibique pri ei, dicat aliquam ad usu. Vim eu aperiam omittam qualisque, sea laoreet electram in. Delectus verterem disputationi ad vim, eos ne inermis molestie consetetur, populo mnesarchum quo te.
Vel te mazim error diceret, per posidonium concludaturque ad. Qui te semper integre, 
Te epicuri iudicabit his. Qui velit senserit constituam at, ad nihil melius numquam qui, eam option appetere in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('10','Ammar','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos ei. Vis consul epicuri consectetuer ne, quo volumus nominavi et. Errem impedit tibique pri ei, dicat aliquam ad usu. Vim eu aperiam omittam qualisque, sea laoreet electram in. Delectus verterem disputationi ad vim, eos ne inermis molestie consetetur, populo mnesarchum quo te.
Vel te mazim error diceret, per posidonium concludaturque ad. Qui te semper integre, an sed in. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.'),
('12','roba','Lorem ipsum dolor sit amet, quo regione salutandi forensibus ei, deserunt contentiones vim ut. Hinc discere ocurreret quo cu, nec aeterno admodum expetenda eu, audiam sanctus definiebas ne sed. Ad eum enim perpetua, in mea autem dolor sanctus. Pericula argumentum reprimique at duo, malorum docendi an sit. Est meis velit vivendo ea.
 Te eam mediocrem conceptam intellegat, nec omnes mediocrem suavitate in, tollit sapientem in est.
Mea error tincidunt democritum ad, ut est ullum zril possit, integre maluisset eos ei. Vis consul epicuri consectetuer ne, quo volumus nominavi et. Errem impedit tibique pri ei, dicat aliquam ad usu. Vim eu aperiam omittam qualisque, sea laoreet electram in. Delectus verterem disputationi ad vim, eos ne inermis molestie consetetur, populo mnesarchum quo te.
Vel te mazim error diceret. Solum hendrerit vulputate ius te, timeam mnesarchum liberavisse duo ea. Graeci iisque no eum, at virtute apeirian appellantur usu. An diam labores invenire nec, duo.')