//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileCan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class CompanyInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        [DisplayName("Working hours")]
        public string WorkingHours { get; set; }
        public string Phone { get; set; }
    }
}
